version: "3"
services:
  client:
    # container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run startprodbackup
    volumes: 
      - .:/app/frontend
      - library_frontend:/app/frontend/node_modules
      - /reactcert/:/app/frontend/reactcert
    ports:
      - "3001:3000"
      - "3002:3000"
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    
volumes:
  library_frontend:
    driver: local