version: "3"
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    volumes: 
      - .:/app/frontend
      - library_frontend:/app/frontend/node_modules
    ports:
      - "3001:3000"
    restart: always
volumes:
  library_frontend:
    driver: local