
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

export const AUTH_USER = 'AUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const EXCEPTION_ERROR = 'EXCEPTION_ERROR'
export const AUTH_CLEAR = 'AUTH_CLEAR'
export const RESET_ERROR = 'RESET_ERROR'
export const AUTH_SITE = 'AUTH_SITE'

export const SWAP_COMPANY = 'SWAP_COMPANY'

export const CREATE_STREAM = 'CREATE_STREAM'
export const FETCH_STREAMS = 'FETCH_STREAMS'
export const FETCH_STREAM = 'FETCH_STREAM'
export const DELETE_STREAM = 'DELETE_STREAM'
export const UPDATE_STREAM = 'UPDATE_STREAM'
export const DELETE_DATA = 'DELETE_DATA'


export const FETCH_SITE = 'FETCH_SITE'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_DASHBOARD = 'FETCH_DASHBOARD'
export const PICKED_DATE = 'PICKED_DATE'
export const PICKED_SITE = 'PICKED_SITE'
export const FETCH_BI = 'FETCH_BI'
export const FETCH_BI_1 = 'FETCH_BI_1'
export const FETCH_BI_2 = 'FETCH_BI_2'
export const FETCH_BI_3 = 'FETCH_BI_3'
export const FETCH_BI_4 = 'FETCH_BI_4'
export const FETCH_BI_5 = 'FETCH_BI_5'
export const FETCH_BI_6 = 'FETCH_BI_6'
export const FETCH_BI_7 = 'FETCH_BI_7'
export const FETCH_BI_8 = 'FETCH_BI_8'
export const FETCH_BI_9 = 'FETCH_BI_9'
export const FETCH_BI_10 = 'FETCH_BI_10'
export const FETCH_BI_11 = 'FETCH_BI_11'
export const FETCH_BI_12 = 'FETCH_BI_12'
export const FETCH_BI_13 = 'FETCH_BI_13'
export const FETCH_BI_14 = 'FETCH_BI_14'
export const RESET_BI_DATA = 'RESET_BI_DATA'
export const RESET_BI_DATA_7 = 'RESET_BI_DATA_7'

export const SPREADSHEET = 'SPREADSHEET'
export const DATAREPORT = 'DATAREPORT'

//Mill\\
export const FETCH_LPH = 'FETCH_LPH'
export const FETCH_LPB = 'FETCH_LPB'
export const FETCH_LISTMILL = 'FETCH_LISTMILL'
export const FETCH_MILL = 'FETCH_MILL'
export const FETCH_RPH = 'FETCH_RPH'
export const FETCH_RPB = 'FETCH_RPB'
export const FETCH_GRADFFB = 'FETCH_GRADFFB'
export const FETCH_TABLEGRAD = 'FETCH_TABLEGRAD'
export const FETCH_BREEDER = 'FETCH_BREEDER'
export const FETCH_JAMTBS = 'FETCH_JAMTBS'
export const FETCH_TABKERJA = 'FETCH_TABKERJA'
export const FETCH_TABLECOST = 'FETCH_TABLECOST'
export const FETCH_TABLETBSOLAH = 'FETCH_TABLETBSOLAH'
export const FETCH_TABCOSTTBSOLAH = 'FETCH_TABCOSTTBSOLAH'
export const FETCH_PALMPROD = 'FETCH_PALMPROD'
export const FETCH_COSTPALMPROD = 'FETCH_COSTPALMPROD'
export const FETCH_OLAHRAWATUMUM = 'FETCH_OLAHRAWATUMUM'
export const FETCH_THISMONTH = 'FETCH_THISMONTH'
export const FETCH_TODATE = 'FETCh_TODATE'

export const FETCH_TABEMP = 'FETCH_TABEMP'
export const FETCH_RANKKERJA = 'FETCH_RANKKERJA'
export const FETCH_RANKEMP = 'FETCH_RANKEMP'
export const FETCH_UMUR = 'FETCH_UMUR'
export const FETCH_GAUGE = 'FETCH_GAUGE'
export const FETCH_GAUGE1 = 'FETCH_GAUGE1'
export const RELOAD_CONTENT = 'RELOAD_CONTENT'

///MillCost\\\\
export const FETCH_BIAYAOLAH = 'FETCH_BIAYAOLAH'
export const FETCH_BIAYAOLAHDETAIL = 'FETCH_BIAYAOLAHDETAIL'

export const FETCH_BIAYARAWAT = 'FETCH_BIAYARAWAT'
export const FETCH_BIAYARAWATDETAIL = 'FETCH_BIAYARAWATDETAIL'

export const FETCH_BIAYAUMUM = 'FETCH_BIAYAUMUM'
export const FETCH_BIAYAUMUMDETAIL = 'FETCH_BIAYAUMUMDETAIL'

///MillCostAllSite\\\\
export const FETCH_BIAYATHISMONTH = 'FETCH_BIAYATHISMONTH'

export const FETCH_BIAYATODATE = 'FETCH_BIAYATODATE'

export const FETCH_MENU = 'FETCH_MENU'
export const ACTIVE_ROUTE = 'ACTIVE_ROUTE'

export const ACTIVE_PROPS = 'ACTIVE_PROPS'

export const FETCH_BANKS = 'FETCH_BANKS'
export const FETCH_BANK = 'FETCH_BANK'

export const UPDATE_LISTDATA = 'UPDATE_LISTDATA'
export const FETCH_LISTDATA = 'FETCH_LISTDATA'
export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATAS = 'FETCH_DATAS'

export const FETCH_DATADETAIL = 'FETCH_DATADETAIL'
export const FETCH_LISTDATADETAIL = 'FETCH_LISTDATADETAIL'
export const FETCH_CHART = 'FETCH_CHART'
export const DATE_FILTER = 'DATE_FILTER'

export const FETCH_LISTCONTENT_ALL = 'FETCH_LISTCONTENT_ALL'
export const FETCH_LISTCONTENT = 'FETCH_LISTCONTENT'
export const UPDATE_LISTCONTENT = 'UPDATE_LISTCONTENT'

export const UPDATE_LISTCONTENT_FAILED = 'UPDATE_LISTCONTENT_FAILED'

export const FETCH_NAV_FILTER = 'FETCH_NAV_FILTER'
export const FETCH_NAV_FILTER_2 = 'FETCH_NAV_FILTER_2'


export const FETCH_DYNAMIC_FILTER = 'FETCH_DYNAMIC_FILTER'
export const SELECT_DYNAMIC_FILTER = 'SELECT_DYNAMIC_FILTER'


export const FETCH_DATAS_PROCESS = 'FETCH_DATAS_PROCESS'

export const FETCH_ERROR = 'FETCH_ERROR'

export const UPDATE_FETCH_DATA = 'UPDATE_FETCH_DATA'

export const FETCH_PVS = 'FETCH_PAYMENTVOUCHERS'
export const FETCH_PVSDTL = 'FETCH_PAYMENTVOUCHERSDETAIL'
export const FETCH_COUNT = 'FETCH_COUNT'
export const FETCH_PAGEINDEX = 'FETCH_PAGEINDEX'
export const FETCH_PAGESIZE = 'FETCH_PAGESIZE'
export const FETCH_SEARCH = 'FETCH_SEARCH'
export const FETCH_PERIOD = 'FETCH_PERIOD'
//ReceiveVoucher
export const FETCH_RVS = 'FETCH_RECEIVEVOUCHERS'
export const FETCH_RVSDTL = 'FETCH_RECEIVEVOUCHERSDETAIL'

export const MODAL_STATE = 'MODAL_STATE'
export const ERROR_MODAL_STATE = 'ERROR_MODAL_STATE'
export const MODAL_ACTION_NEXT = 'MODAL_ACTION_NEXT'
export const CHANGE_MODAL_ITEM_STATE = 'CHANGE_MODAL_ITEM_STATE'


export const MODAL_ON_LOADING = 'MODAL_ON_LOADING'

export const RESET_MODAL = 'RESET_MODAL'
export const RESET_MODAL_ONLY = 'RESET_MODAL_ONLY'
export const MODAL_CONTENT_CHANGES = 'MODAL_CONTENT_CHANGES'


export const SEND_MESSAGE = 'SEND_MESSAGE'

export const SAVE = 'SAVE_DATA'
export const UPDATE = 'UPDATE_DATA'
export const DELETE = 'DELETE_DATA'
export const PROCESS = 'PROCESS_DATA'
export const APPROVE = 'APPROVE_DATA'
export const REJECT = 'REJECT_DATA'


export const FAILED_LOV = 'FAILED_LOV'
export const OPEN_LOV = 'OPEN_LOV'
export const FETCH_LOVS = 'FETCH_LOV'
export const VALUE_SELECTED = 'VALUE_SELECTED'
export const RESET_LOV = 'RESET_LOV'

export const LOADING_FIELD_FORMULA = 'LOADING_FIELD_FORMULA'

export const VISIBLE_SIDE = 'VISIBLE_SIDE'


export const FETCH_SELECT = 'FETCH_SELECT'
export const RESET_SELECT = 'RESET_SELECT'
export const FAILED_SELECT = 'FAILED_SELECT'

export const UPDATE_NAV = 'UPDATE_NAV'
export const UPDATE_NAV_SEARCH = 'UPDATE_NAV_SEARCH'
export const UPDATE_NAV_SEARCH2 = 'UPDATE_NAV_SEARCH2'
export const UPDATE_NAV_PERIOD = 'UPDATE_NAV_PERIOD'
export const UPDATE_NAV_PERIOD_NOW = 'UPDATE_NAV_PERIOD_NOW'

export const RESET_DETAIL_DATA = 'RESET_DETAIL_DATA'
export const RESET_ERROR_MODAL_STATE = 'RESET_ERROR_MODAL_STATE'
export const RESET_URL_PREVIEW = 'RESET_URL_PREVIEW'
export const RESET_URL_PREVIEW_ARRAY = 'RESET_URL_PREVIEW_ARRAY'

export const POST_DATA = 'POST_DATA'
export const SUBMIT_DATA = 'SUBMIT_DATA'

export const MODAL_BUTTON_LOADING = 'MODAL_BUTTON_LOADING'

export const RESEARCH_LOVDATA = 'RESEARCH_LOVDATA'
export const RESEARCH_LOVDATA_OK = 'RESEARCH_LOVDATA_OK'
export const RESEARCH_LOVDATA_FAIL = 'RESEARCH_LOVDATA_FAILED'

export const DETAIL_LOVDATA_APPEND = 'DETAIL_LOVDATA_APPEND'
export const DETAIL_LOVDATA = 'DETAIL_LOVDATA'
export const DETAIL_LOVDATA_OK = 'DETAIL_LOVDATA_OK'
export const DETAIL_LOVDATA_FAIL = 'DETAIL_LOVDATA_FAILED'


export const MODAL_SEARCH_VALUE = 'MODAL_SEARCH_VALUE'

export const FAILED_LOVDATA = 'FAILED_DATA'
export const OPEN_LOVDATA = 'OPEN_DATA'
export const FETCH_LOVDATA = 'FETCH_DATA'

export const CLEAN_QUERY = "CLEAN_QUERY"
export const START_SEARCH = "START_SEARCH"
export const FINISH_SEARCH = "FINISH_SEARCH"
export const UPDATE_SELECTION = "UPDATE_SELECTION"

export const DATA_TO_EDIT = 'DATA_TO_EDIT'
export const QR_COMPONENT = 'QR_COMPONENT'
export const RESET_QR_COMPONENT = 'RESET_QR_COMPONENT'
export const WEBCAM_COMPONENT = 'WEBCAM_COMPONENT'
export const RESET_WEBCAM_COMPONENT = 'RESET_WEBCAM_COMPONENT'


export const RESET_TRANSACTION_ERROR = 'RESET_TRANSACTION_ERROR'

export const FETCH_TEMP_DATA = 'FETCH_TEMP_DATA'
export const FETCH_URLPREVIEW_DATA = 'FETCH_URLPREVIEW_DATA'
export const FETCH_URLPREVIEW_DATA_ARRAY = 'FETCH_URLPREVIEW_DATA_ARRAY'

export const SET_TRANSACTION_STATUS = 'SET_TRANSACTION_STATUS'
export const SET_TRANSACTION_INFO = 'SET_TRANSACTION_INFO'

export const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
export const SET_LOADING_MESSAGE = 'SET_LOADING_MESSAGE'


export const SET_VALIDATION_SCHEMA = 'SET_VALIDATION_SCHEMA'


export const SET_DEFAULT_VALUE = 'SET_DEFAULT_VALUE'

export const DOCUMENT_TITLE = 'DOCUMENT_TITLE'

export const ACTION_LABEL = 'ACTION_LABEL'

export const RESET_TRX = 'RESET_TRX'

export const NAV_AFTER_INSERT = 'NAV_AFTER_INSERT'

export const POST_RESET = 'POST_RESET'

export const NAV_AFTER_UPDATE = 'NAV_AFTER_UPDATE'


export const SET_TRX_ID = 'SET_TRX_ID'

export const DECREMENT_TRX_ID = 'DECREMENT_TRX_ID'

export const INCREMENT_TRX_ID = 'INCREMENT_TRX_ID'

export const RESET_TRX_ID = 'RESET_TRX_ID'


export const RESET_NAV = 'RESET_NAV'

export const DELETE_LIST = 'DELETE_LIST'
export const HIDDEN_LIST = 'HIDDEN_LIST'

export const FORCED_RENDER_GRID = 'FORCED_RENDER_GRID'

export const RESET_DELETE_LIST = 'RESET_DELETE_LIST'
export const RESET_HIDDEN_LIST = 'RESET_HIDDEN_LIST'

export const MODAL_TRX_OPEN = 'MODAL_TRX_OPEN'
export const MODAL_TRX_CLOSE = 'MODAL_TRX_CLOSE'

export const GRID_EDIT_TRUE = 'GRID_EDIT_TRUE'
export const GRID_EDIT_RESET = 'GRID_EDIT_RESET'
export const GRID_EDIT_FALSE = 'GRID_EDIT_FALSE'

export const SINGLE_LOAD_FALSE = 'SINGLE_LOAD_FALSE'
export const SINGLE_LOAD_TRUE = 'SINGLE_LOAD_TRUE'

export const GRID_MINIMIZE = 'GRID_MINIMIZE'
export const GRID_MAXIMIZE = 'GRID_MAXIMIZE'

export const ADD_NUMBER_COUNT = 'ADD_NUMBER_COUNT'

export const SET_GRID_STATUS = 'SET_GRID_STATUS'

export const RESET_ACTIVE_ROW = 'RESET_ACTIVE_ROW'
export const SET_ACTIVE_ROW = 'SET_ACTIVE_ROW'
export const SET_ACTIVE_DATA_ROW = 'SET_ACTIVE_DATA_ROW'
export const SET_UPDATED_LINK_DATA = 'SET_UPDATED_LINK_DATA'

export const SET_SELECTED_ROW = 'SET_SELECTED_ROW'

export const FETCH_USER_AUTH_SITE = 'FETCH_USER_AUTH_SITE'

export const FETCH_USER_AUTH_SITE_FAIL = 'FETCH_USER_AUTH_SITE_FAILE'

export const DATA_LINK_SUBMITED = 'DATA_LINK_SUBMITED'

export const UPDATE_DATA_LINK_SUBMITED = 'UPDATE_DATA_LINK_SUBMITED'

export const REACT_SELECT_OPEN = 'REACT_SELECT_OPEN'

export const SET_DATA_LOADING = 'SET_DATA_LOADING'


export const ACTIVE_GRID_COLUMN = 'ACTIVE_GRID_COLUMN'


export const GENERATE_DATA = 'GENERATE_DATA'

export const GENERATE_SUBDETAIL = 'GENERATE_SUBDETAIL'


export const FILTER_LIST = 'FILTER_LIST'

export const UPDATE_LISTDATADETAIL = 'UPDATE_LISTDATADETAIL'

export const ON_PROCESS = 'ON_PROCESS'


export const SET_ACCORDION = 'SET_ACCORDION'


export const RESET_AGRO_DATA = 'RESET_AGRO_DATA'
export const FETCH_ACTBUDGET = 'FETCH_ACTBUDGET'
export const RESET_ACT_POT = 'RESET_ACT_POT'
export const FETCH_ACTPOT = 'FETCH_ACTPOT'
export const FETCH_ACTBUDGETMAP = 'FETCH_ACTBUDGETMAP'
export const FETCH_ACTPOTMAP = 'FETCH_ACTPOTMAP'
export const RESET_AREASTATEMENT = 'RESET_AREASTATEMENT'
export const FETCH_AREASTATEMENT = 'FETCH_AREASTATEMENT'
export const RESET_PRODUKSIBULANANDETAIL = 'RESET_PRODUKSIBULANANDETAIL'
export const FETCH_PRODUKSIBULANANDETAIL = 'FETCH_PRODUKSIBULANANDETAIL'
export const RESET_PRODUKSIBULANAN = 'RESET_PRODUKSIBULANAN'
export const RESET_PRODUKSIHARIAN = 'RESET_PRODUKSIHARIAN'
export const FETCH_PRODUKSIBULANAN = 'FETCH_PRODUKSIBULANAN'
export const FETCH_PRODUKSIHARIAN = 'FETCH_PRODUKSIHARIAN'

export const RESET_YIELDBYAGE = 'RESET_YIELDBYAGE'
export const FETCH_YIELDBYAGE = 'FETCH_YIELDBYAGE'

export const RESET_YIELDPOTENSI = 'RESET_YIELDPOTENSI'
export const FETCH_YIELDPOTENSI = 'FETCH_YIELDPOTENSI'


