export const Appresources = {
    TRANSACTION_ALERT: {
        SAVE_CONFIRMATION: 'Data Will Be Saved, Are You Sure.?'
        , SAVE_APPROVED_CONFIRMATION: `Data Will Be Saved & Approved , Are You Sure.?`
        , SAVE_SUCCESS: 'Transaction Saving Successfully'
        , SAVE_FAILED: 'Transaction Is Not Saved'
        , SAVE_PROCESS: 'Saving Transaction, Please Wait....'
        , UPDATE_CONFIRMATION: 'Data Will Be Updated, Are You Sure.?'
        , CUSTOM_CONFIRMATION: 'Custom Message Here...'
        , CONFIRMATION_NOTES: 'Confirmation with notes'
        , CONFIRMATION_OR_REJECT: 'Confirmation or Rejection'
        , DATE_CONFIRMATION: 'Date Confirmation...'
        , UPDATE_PROCESS: 'Update Transaction, Please Wait....'
        , UPDATE_SUCCESS: 'Update Transaction Success'
        , UPDATE_FAILED: 'Update Transaction Failed'
        , DELETE_CONFIRMATION: 'Data Will Be Deleted, Are You Sure.?'
        , DELETE_SUCCESS: 'Transaction Deleted'
        , DELETE_FAILED: 'Unable To Delete Transaction'
        , UNAUTH_TRX: 'Unauthorized Transaction'
        , LOV: 'List Of Values'
        , LOV_ACTION: 'List Of Data Action'
        , LOV_ACTION_COMPONENT: 'List Of Data Component'
        , LOV_REPORT_DATA: 'List Of Report Data'
        , LOV_LINKED_DATA: 'List Of Data Linked'
        , LOV_LINKED_DATA_HEADER: 'List Of Data Linked Header'
        , LOV_VIEW_DATA: 'List Of View Data'
        , LOV_VIEW_DATA_BASIC: 'List Of View Data Basic'
        , DIALOG_CONFIRM: 'Dialog Confirm'
        , DIALOG_DATA: 'Dialog Data'
        , DIALOG_LOADING: 'Dialog Loading'
        , DIALOG_WEBCAM: 'Dialog Webcam'
        , DIALOG_SCAN_QR: 'Dialog Scan QR'
        , DIALOG_COMPONENT_QR: 'Dialog Component QR'
        , DIALOG_COMPANY: 'Dialog List Company'
        , LOADING_STATUS: 'Loading'
        , LOADING_MDOULES: 'Preparing ePlant Modules...'
        , LOADING_FAILED: 'Failed'
        , TRANSACTION_ERROR: 'Transaction Error.'
        , ROWS_DUPLICATE: 'Duplicate Rows in Row '
        , TELL_ADMIN: `Check Internet Connection or Contact Your Administrator and Refresh This Page`
        , INPUT_ON_DIALOG: 'Input On Dialog'
        , APPROVE_CONFIRMATION: 'Transaction Will Be Approved, Are You Sure.?'
        , CHANGE_DATE_FILTER: 'Change Date Filter'
    },
    BUTTON_LABEL: {
        LABEL_SAVE: 'Save'
        , LABEL_UPDATE: 'Update'
        , LABEL_DELETE: 'Delete'
        , LABEL_CANCEL: 'Cancel'
        , LABEL_PROCESS: 'Process'
        , LABEL_REJECT: 'Reject'
        , LABEL_REVISI: 'Revise'
        , LABEL_LANJUT_REJECT: 'Submit Rejection'
        , LABEL_LANJUT: 'Lanjut'
        , LABEL_LANJUT_TRX: 'Lanjut Input Transaksi'
        , LABEL_APPROVE: 'Approve'
        , LABEL_KIRIM: 'Kirim'
    },
    STATUS: {
        FAILED: 'failed',
        SUCCESS: 'success'
    },
    APP_TITLES: 'ePlant-USTP'
}